//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ETLCenter.ETLEmployeeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ETLCenterEmployeeServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ETLCenterEmployeeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EmployeeCreationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectEmployeeDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ETLCenterEmployeeService() {
            this.Url = global::ETLCenter.Properties.Settings.Default.ETLCenter_ETLEmployeeService_ETLCenterEmployeeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EmployeeCreationCompletedEventHandler EmployeeCreationCompleted;
        
        /// <remarks/>
        public event SelectEmployeeDetailsCompletedEventHandler SelectEmployeeDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmployeeCreation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EmployeeCreation(int ID_Employee, string EmpName, string EmpPassword, string EmpEmail, int EmpIsActive, int EmpIsDelete, int EnteredBy, int ModifiedBy, int Action) {
            object[] results = this.Invoke("EmployeeCreation", new object[] {
                        ID_Employee,
                        EmpName,
                        EmpPassword,
                        EmpEmail,
                        EmpIsActive,
                        EmpIsDelete,
                        EnteredBy,
                        ModifiedBy,
                        Action});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EmployeeCreationAsync(int ID_Employee, string EmpName, string EmpPassword, string EmpEmail, int EmpIsActive, int EmpIsDelete, int EnteredBy, int ModifiedBy, int Action) {
            this.EmployeeCreationAsync(ID_Employee, EmpName, EmpPassword, EmpEmail, EmpIsActive, EmpIsDelete, EnteredBy, ModifiedBy, Action, null);
        }
        
        /// <remarks/>
        public void EmployeeCreationAsync(int ID_Employee, string EmpName, string EmpPassword, string EmpEmail, int EmpIsActive, int EmpIsDelete, int EnteredBy, int ModifiedBy, int Action, object userState) {
            if ((this.EmployeeCreationOperationCompleted == null)) {
                this.EmployeeCreationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeCreationOperationCompleted);
            }
            this.InvokeAsync("EmployeeCreation", new object[] {
                        ID_Employee,
                        EmpName,
                        EmpPassword,
                        EmpEmail,
                        EmpIsActive,
                        EmpIsDelete,
                        EnteredBy,
                        ModifiedBy,
                        Action}, this.EmployeeCreationOperationCompleted, userState);
        }
        
        private void OnEmployeeCreationOperationCompleted(object arg) {
            if ((this.EmployeeCreationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeCreationCompleted(this, new EmployeeCreationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectEmployeeDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelectEmployeeDetails() {
            object[] results = this.Invoke("SelectEmployeeDetails", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelectEmployeeDetailsAsync() {
            this.SelectEmployeeDetailsAsync(null);
        }
        
        /// <remarks/>
        public void SelectEmployeeDetailsAsync(object userState) {
            if ((this.SelectEmployeeDetailsOperationCompleted == null)) {
                this.SelectEmployeeDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectEmployeeDetailsOperationCompleted);
            }
            this.InvokeAsync("SelectEmployeeDetails", new object[0], this.SelectEmployeeDetailsOperationCompleted, userState);
        }
        
        private void OnSelectEmployeeDetailsOperationCompleted(object arg) {
            if ((this.SelectEmployeeDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectEmployeeDetailsCompleted(this, new SelectEmployeeDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void EmployeeCreationCompletedEventHandler(object sender, EmployeeCreationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmployeeCreationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmployeeCreationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SelectEmployeeDetailsCompletedEventHandler(object sender, SelectEmployeeDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectEmployeeDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectEmployeeDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591